export const CONTRACT_DETAILS_REQUEST = "CONTRACT_DETAILS_REQUEST"
export const CONTRACT_DETAILS_SUCCESS = "CONTRACT_DETAILS_SUCCESS"
export const CONTRACT_DETAILS_FAIL = "CONTRACT_DETAILS_FAIL"
export const CONTRACT_DETAILS_RESET = "CONTRACT_DETAILS_RESET"
